language: node_js
node_js:
  - "8"
  - "lts/*"
branches:
  except:
    - docs
cache: 
  directories:
    - "node_modules"
  yarn: true
scripts:
  - yarn global add codecov
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF __tests__/coverage/
  - codecov